.\" Manpage for pam_checkhomedir
.\" Contact mcoccimiglio@rice.edu to correct errors or typos.
.TH man 8 "19 Aug 2019" "0.0.4" "pam_checkhomedir man page"
.SH NAME
pam_checkhomedir \- PAM Module to check that a user's home directory is present on the system.
.SH SYNOPSIS
n/a - Used by pam.  Takes no paramaters.
.SH DESCRIPTION

NOTE: This package currently works but is considered BETA.

The design of this PAM Module is to test for the presence of the user's home
directory.  If the Home Directory is not found we return a non\-PAM_SUCCESS
return code. Basically the module pulls the proper $HOME from getpwnam(user)
and does a "Blind Open" ( opendir( struct_getpwdnam\->pw_dir ) ). We DO NOT
first test to see if the directory exists. This is deliberate. If the user's
home directory is auto\-mounted (e.g. autofs) then it will not show if we
try to pre\-test for its existence. We want the underlying file system/mounts
to intercept the open request, block, and mount the home directory before
releasing the I/O blocking.
.SH OPTIONS
The pam_checkhomedir does not take any options.
.SH SEE ALSO
pam(8)
.SH BUGS
Security NOTE: We currently do NOT test ownership or permissions at this time.
We do however test twice (with a delay) if the first one fails. Depending on
how you configure PAM the user's home directory may mount regardless if the
users credential are valid. YMMV
.SH AUTHOR
Mark Coccimiglio (mcoccimiglio@rice.edu)
